name: Update Docker image

on:
  push:
    branches:
      - master
    tags:
      - '*'  # This triggers the action on all tag pushes

jobs:
  publish-docker-image:
    if: github.repository_owner == 'gbdev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push the master container image
        run: |
          docker build . --tag ghcr.io/gbdev/rgbds:master
          docker push ghcr.io/gbdev/rgbds:master
        
      - name: Tag release container image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/gbdev/rgbds:master ghcr.io/gbdev/rgbds:$TAG_NAME
          docker push ghcr.io/gbdev/rgbds:$TAG_NAME
